version: '3'

services:

  mysql:
    container_name: database
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ALLOW_EMPTY_PASSWORD: ok
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - database:/var/lib/mysql

  api:
    container_name: api
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DB_TYPE=${DB_TYPE}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DB=${DB_NAME}
      - MYSQL_PORT=${MYSQL_PORT}
      - APP_EXPIRES=${APP_EXPIRES}
      - APP_PORT=${APP_PORT}
    image: noah/e-shopper:latest
    ports:
      - '3434:3434'
    expose:
      - '3434'
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mysql
    links:
      - "mysql:database"

volumes:
  database:
